package model;
// Generated Aug 21, 2016 7:59:02 PM by Hibernate Tools 5.1.0.Beta1

/**
 * WsolTables generated by hbm2java
 */
public class WsolTables implements java.io.Serializable {

	private Integer id;
	private String databasename;
	private String tablename;
	private String type;

	public WsolTables() {
	}

	public WsolTables(String databasename, String tablename, String type) {
		this.databasename = databasename;
		this.tablename = tablename;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDatabasename() {
		return this.databasename;
	}

	public void setDatabasename(String databasename) {
		this.databasename = databasename;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
